@ClientApplcationBFF_HostAddress = http://localhost:1147

### Create a new patient
POST {{ClientApplcationBFF_HostAddress}}/api/catalog/patients
Content-Type: application/json

{
  "name": "Moshe Cohen",
  "birthdate": "1989-01-01T00:00:00",
  "gender": "male"
}

###
GET {{ClientApplcationBFF_HostAddress}}/api/catalog/patients
Content-Type: application/json


###
GET {{ClientApplcationBFF_HostAddress}}/api/catalog/patients/2
Content-Type: application/json