@Patients.CatalogAPI_HostAddress = https://localhost:7143

GET {{Patients.CatalogAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Patients.CatalogAPI_HostAddress}}/Patients

###
